### ISSUE TITLE
Can't controll Go1 through ROS

### ISSUE THREAD

**Issue by despargy** [Taucrates/Go1_ros_to_real#1]
Hey,

Thank you for your precious work!

I would like to ask for your help since I follow your repo instructions but the robot go1 does not move.

Following the step:
a) set Ethernet connection between my laptop and go1 ( ping ok )
b) $roslaunch unitree_legged_real real.launch  from my laptop
c1) $rosrun teleop_twist_keyboard_cpp teleop_twist_keyboard
 or c2) pub to cmd_vel, receiving message "Robot moves", but the real robot doesn't do anything.

I would greatly appreciate if you could give me any advice. 
Thank you!

**Comment by Taucrates** [comment]
Hi,

Did you compile the package unitree_legged_sdk as is indicated in their own github?

Here the commands inside the package:

mkdir build
cd build
cmake ../
make

I hope it works, I had some troubles with different computers, and I'm trying to solve the issue.

**Comment by despargy** [comment]
After contacting with Unitree support team, I was informed that it was the main controller and so I had to replace it.

Thank you!
